Fix build errors on some VS installations due to a missing header.
For w/e, when running the build in a GitHub runner, it throws an error
of `error C2065: '_finddata_t'`, whilst on other machines it builds just
fine. Therefore explictly including `io.h` header should fix this until
we move away to std::filesystem, then we can remove this.